### ISSUE TITLE
Feature Request - Native Leanback App for Android TV? 

### ISSUE THREAD

**Issue by Pentaphon** [OdyseeTeam/odysee-android#380] opened 2022-10-27 22:48 UTC
The current web wrapper version of Odysee is basically the same one as we browse on a desktop web browser. Can we get a native Leanback App for Android TV so we can have a faster, more stable Odysee experience with full remote support like we have with Youtube?

**Comment by kekkyojin** [comment] 2022-10-27 23:20
Duplicate of #120

**Closed by kekkyojin** 2022-10-27 23:20 UTC
